import { Bot, Check, CircleAlert, CircleCheck, CircleDashed, Clock3, LoaderCircle, ShieldX, Sparkles } from "lucide-react";
import { useState } from "react";
import type { ReactElement } from "react";
import type { AiValidation } from "../../../src/ai/ai-types";
import type { DashboardState } from "../../../src/dashboard/dashboard-types";
import { BeautifulContextRow, BeautifulInsightList, BeautifulLoadingState, BeautifulStatusChip, BeautifulTaskRows, type BeautifulTask, type BeautifulTone } from "../beautiful-ui";
import { formatTime } from "../ui";

function recommendationTone(value: AiValidation["recommendation"]): BeautifulTone { return value === "BUY" ? "positive" : value === "SELL" ? "negative" : "warning"; }
function ruleTone(value: AiValidation["ruleStatus"]): BeautifulTone { return value === "PASS" ? "positive" : value === "FAIL" ? "negative" : "warning"; }
function ruleLabel(value: AiValidation["ruleStatus"]): string { return value === "PASS" ? "规则通过" : value === "FAIL" ? "规则不通过" : "规则不确定"; }
function ResultIcon({ result }: { result: AiValidation["recommendation"] }): ReactElement { return result === "BUY" ? <CircleCheck size={15} /> : result === "SELL" ? <ShieldX size={15} /> : <CircleAlert size={15} />; }

export function AiAnalysisPanel({ state }: { state: DashboardState }): ReactElement {
  const [reviewing, setReviewing] = useState(false);
  const review = async (): Promise<void> => { setReviewing(true); try { const response = await fetch("/api/ai-review", { method: "POST" }); if (!response.ok) { const body = await response.json() as { error?: string }; window.alert(body.error ?? "AI 分析失败"); } } catch (error) { window.alert(error instanceof Error ? error.message : "AI 分析失败"); } finally { setReviewing(false); } };
  const latest = state.ai.latest;
  const stages = [
    { title: "读取已收盘 K 线", detail: `${state.market.recentCandles.length} 根上下文 · ${state.interval}`, done: Boolean(state.market.latestCandle) },
    { title: "确定性策略评估", detail: state.strategy.entrySignal ? `${state.strategy.buy} 买入候选` : "无买入候选，不允许 AI 创造信号", done: state.strategy.entrySignal !== null },
    { title: "趋势与持仓门控", detail: `${state.strategy.trendFilter ? "趋势通过" : "趋势未通过"} · ${state.position ? "已有持仓" : "空仓"}`, done: true },
    { title: "LangChain 模型审核", detail: latest ? `${latest.model} · ${latest.source}` : "尚未运行", done: latest?.source === "langchain", error: latest?.source === "error" },
    { title: "执行权限判定", detail: latest?.allowEntry ? "AI 允许确定性候选进入风控" : "不允许入场；AI 不拥有下单权限", done: Boolean(latest) },
  ];
  const taskRows: BeautifulTask[] = stages.map((stage, index) => ({ title: stage.title, detail: stage.detail, state: reviewing && index === 3 ? "running" : stage.error ? "error" : stage.done ? "done" : "pending" }));
  return <section className="terminal-panel p-4">
    <div className="flex flex-wrap items-start gap-3"><div className="grid h-9 w-9 place-items-center rounded bg-cyan/10 text-cyan"><Bot size={19} /></div><div><span className="terminal-eyebrow">LANGCHAIN REVIEW</span><h2 className="terminal-title">AI 行情与策略审核</h2><p className="m-0 mt-1 text-[10px] text-muted">{state.ai.model} · {state.ai.decisionMode === "veto" ? "否决模式" : "建议模式"} · 不直接创建订单</p></div><div className="ml-auto flex items-center gap-2"><BeautifulStatusChip label={state.ai.enabled ? "已启用" : "未启用"} tone={state.ai.enabled ? "positive" : "neutral"} icon={state.ai.enabled ? <CircleCheck size={12} /> : <CircleAlert size={12} />} /><button className="inline-flex h-8 items-center gap-2 rounded border border-cyan/35 bg-cyan/8 px-3 text-xs text-cyan disabled:opacity-40" onClick={() => void review()} disabled={!state.ai.enabled || reviewing}>{reviewing ? <LoaderCircle size={14} className="animate-spin" /> : <Sparkles size={14} />}{reviewing ? "分析中" : latest ? "再次分析" : "立即分析"}</button></div></div>
    <div className="bui-thinking-trace mt-4"><div className="bui-thinking-heading"><span><Sparkles size={13} />Agent Thinking Trace</span><span>{reviewing ? "运行中" : latest ? "已完成" : "等待触发"}</span></div>{reviewing && <BeautifulLoadingState label="AI 正在读取行情、审核策略并监控订单" />}<BeautifulTaskRows tasks={taskRows} /></div>
    {latest ? <div className="mt-4"><div className="bui-recommendation"><div className="bui-recommendation-main"><span className={`bui-recommendation-icon ${recommendationTone(latest.recommendation)}`}><ResultIcon result={latest.recommendation} /></span><div><span className="bui-kicker">模型判断</span><strong>{latest.recommendation === "BUY" ? "买入建议" : latest.recommendation === "SELL" ? "卖出建议" : "观望"}</strong></div></div><div className="bui-confidence"><span>置信度</span><strong>{Math.round(latest.confidence * 100)}%</strong><div className="bui-confidence-track"><span style={{ width: `${Math.round(latest.confidence * 100)}%` }} /></div></div></div><div className="bui-chip-row"><BeautifulStatusChip label={ruleLabel(latest.ruleStatus)} tone={ruleTone(latest.ruleStatus)} icon={<CircleCheck size={13} />} /><BeautifulStatusChip label={latest.allowEntry ? "允许入场" : "不允许入场"} tone={latest.allowEntry ? "positive" : "warning"} /><span className="bui-generated"><Clock3 size={13} />{formatTime(latest.generatedAt)}</span></div><p className="bui-summary">{latest.summary}</p><div className="bui-context-grid"><BeautifulContextRow label="交易对" value={state.symbol} /><BeautifulContextRow label="审核来源" value={latest.source === "error" ? "异常回退" : "LangChain"} tone={latest.source === "error" ? "negative" : "info"} /><BeautifulContextRow label="入场门" value={state.ai.decisionMode === "veto" ? "AI 必须放行" : "确定性策略"} /><BeautifulContextRow label="判断失效" value={latest.invalidation} tone="warning" /></div><div className="bui-insight-grid"><BeautifulInsightList title="支持证据" items={latest.evidence} tone="positive" emptyText="模型未提供支持证据" /><BeautifulInsightList title="风险与冲突" items={latest.risks} tone="negative" emptyText="模型未识别额外风险" /></div><details className="mt-3 border-t border-line pt-3"><summary className="cursor-pointer text-xs text-muted">历史审核记录 ({state.ai.history.length})</summary><div className="mt-2 grid gap-1.5">{state.ai.history.slice(1, 6).map((item) => <div key={item.generatedAt} className="flex items-center gap-2 rounded bg-bg/40 px-2 py-2 text-[10px]"><span className="font-mono text-muted">{formatTime(item.generatedAt)}</span><span>{item.recommendation} · {item.ruleStatus}</span><span className="ml-auto text-muted">{Math.round(item.confidence * 100)}%</span></div>)}</div></details></div> : <div className="mt-4 rounded border border-dashed border-line p-6 text-center text-xs text-muted">点击“立即分析”，审核最近一根已收盘 K 线和当前策略状态。</div>}
  </section>;
}
