import { Crosshair, Maximize2 } from "lucide-react";
import type { ReactElement } from "react";
import type { DashboardState } from "../../../src/dashboard/dashboard-types";
import { MarketChart } from "../MarketChart";
const intervals = [{ value: "1h", label: "1 小时" }, { value: "1d", label: "1 天" }, { value: "1w", label: "1 周" }, { value: "1M", label: "1 个月" }, { value: "1y", label: "1 年" }];
export function MarketWorkspace({ state, onIntervalChange }: { state: DashboardState; onIntervalChange: (interval: string) => void }): ReactElement {
  const candle = state.market.latestCandle;
  return <section className="terminal-panel min-w-0 overflow-hidden"><div className="flex min-h-13 flex-wrap items-center gap-3 border-b border-line px-4 py-2"><Crosshair size={15} className="text-primary" /><strong className="text-sm">{state.symbol}</strong><span className="text-xs text-muted">· {state.interval} · {state.platform.toUpperCase()}</span>{candle && <div className="hidden gap-3 text-[10px] lg:flex"><span>开 <b>{candle.open.toFixed(2)}</b></span><span>高 <b className="text-profit">{candle.high.toFixed(2)}</b></span><span>低 <b className="text-loss">{candle.low.toFixed(2)}</b></span><span>收 <b>{candle.close.toFixed(2)}</b></span></div>}<Maximize2 size={14} className="ml-auto text-muted" /></div><MarketChart state={state} heightClassName="h-[430px] min-h-[360px]" levels={[...(state.strategy.support ? [{ price: state.strategy.support, title: "支撑", color: "#F59E0B" }] : []), ...(state.strategy.resistance ? [{ price: state.strategy.resistance, title: "阻力", color: "#22D3EE" }] : [])]} /><div className="flex items-center gap-1 border-t border-line px-3 py-2">{intervals.map((interval) => <button key={interval.value} className={`rounded px-3 py-1.5 text-xs ${state.interval === interval.value ? "bg-primary/15 text-primary" : "text-muted hover:bg-hover"}`} onClick={() => onIntervalChange(interval.value)}>{interval.label}</button>)}<span className="ml-auto text-[10px] text-muted">{state.market.candleCount} 根 K 线 · ticker 实时更新</span></div></section>;
}
