import { CheckCircle2, CircleDashed, ShieldAlert, TrendingUp } from "lucide-react";
import type { ReactElement } from "react";
import type { DashboardState, StrategyDashboardSummary } from "../../../src/dashboard/dashboard-types";
import { formatMoney } from "../ui";

export function StrategyStatusPanel({ state }: { state: DashboardState }): ReactElement {
  const strategy = state.strategies.find((item) => item.id === "gushi-ma");
  const currentRule = state.strategy.buy ?? state.strategy.sell ?? "等待法则触发";
  const checks = [
    { label: "均线趋势过滤", value: state.strategy.trendFilter === null ? "等待指标" : state.strategy.trendFilter ? "趋势条件成立" : "趋势条件未成立", pass: state.strategy.trendFilter === true },
    { label: "入场信号", value: state.strategy.entrySignal ? `${state.strategy.buy} 买入候选` : "当前无确定性买入候选", pass: state.strategy.entrySignal === true },
    { label: "持仓门控", value: state.position ? "已有持仓，禁止重复入场" : "当前允许评估新仓位", pass: !state.position },
    { label: "AI 审核门控", value: state.ai.latest ? `${state.ai.latest.ruleStatus} · ${state.ai.latest.allowEntry ? "允许入场" : "不放行"}` : "等待 AI 审核", pass: state.ai.latest?.allowEntry === true },
  ];
  return <section className="terminal-panel p-4"><div className="flex items-start justify-between"><div><span className="terminal-eyebrow">STRATEGY ENGINE</span><h2 className="terminal-title">策略状态</h2></div><span className={`terminal-status-pill ${strategy?.status === "running" ? "bg-profit/10 text-profit" : "bg-warning/10 text-warning"}`}>{strategy?.status === "running" ? "运行中" : "未运行"}</span></div><div className="mt-3 grid gap-2">{state.strategies.map((item) => <StrategyBadge key={item.id} strategy={item} active={item.id === "gushi-ma"} />)}</div><div className="mt-4 grid grid-cols-2 gap-3 border-y border-line py-4"><div><span className="terminal-label">趋势方向</span><div className={`mt-2 flex items-center gap-2 text-lg ${state.strategy.trendFilter ? "text-profit" : "text-muted"}`}><TrendingUp size={19} />{state.strategy.trendFilter ? "多头趋势" : "等待确认"}</div></div><div><span className="terminal-label">当前法则</span><div className="mt-2 text-lg text-cyan">{currentRule}</div></div></div><div className="mt-3 grid gap-1.5">{checks.map((check) => <div key={check.label} className="flex items-center gap-3 rounded border border-line bg-bg/35 px-3 py-2.5"><span className={check.pass ? "text-profit" : "text-muted"}>{check.pass ? <CheckCircle2 size={15} /> : <CircleDashed size={15} />}</span><span className="min-w-25 text-[11px] text-muted">{check.label}</span><span className="ml-auto text-right text-xs">{check.value}</span></div>)}</div><div className="mt-3 grid grid-cols-2 gap-2"><Level label="支撑位" value={state.strategy.support} /><Level label="阻力位" value={state.strategy.resistance} /></div>{state.connection.error && <div className="mt-3 flex gap-2 rounded border border-loss/30 bg-loss/8 p-3 text-xs text-loss"><ShieldAlert size={15} />{state.connection.error}</div>}</section>;
}
function StrategyBadge({ strategy, active }: { strategy: StrategyDashboardSummary; active: boolean }): ReactElement { return <div className={`flex items-center gap-3 rounded border px-3 py-2 ${active ? "border-primary/35 bg-primary/6" : "border-line bg-bg/30"}`}><span className={`h-1.5 w-1.5 rounded-full ${active && strategy.status === "running" ? "bg-profit" : "bg-muted"}`} /><div className="min-w-0 flex-1"><strong className="block truncate text-xs">{strategy.name}</strong><span className="text-[10px] text-muted">{active ? "当前运行引擎" : "已注册 · 待接入运行时"} · {strategy.category}</span></div><span className={`text-[10px] ${active && strategy.status === "running" ? "text-profit" : "text-muted"}`}>{active && strategy.status === "running" ? "运行中" : "待启用"}</span></div>; }
function Level({ label, value }: { label: string; value: number | null }): ReactElement { return <div className="rounded border border-line p-2.5"><span className="terminal-label">{label}</span><strong className="mt-1 block font-mono text-sm">{value ? formatMoney(value) : "--"}</strong></div>; }
