import { Modal, Select } from "@douyinfe/semi-ui";
import { ArrowDownToLine, ArrowUpFromLine, Brain, Calculator, CheckCircle2 } from "lucide-react";
import { useState } from "react";
import type { ReactElement } from "react";
import type { DashboardState } from "../../../src/dashboard/dashboard-types";
const options = ["1h", "1d", "1w", "1M", "1y"].map((value) => ({ value, label: value }));
const leverages = [1, 2, 3, 5, 10, 20, 50, 100].map((value) => ({ value: String(value), label: `${value}x` }));
export function TradeControl({ state }: { state: DashboardState }): ReactElement {
  const [open, setOpen] = useState(false); const [strategyId, setStrategyId] = useState(state.strategies[0]?.id ?? "gushi-ma"); const [interval, setInterval] = useState(state.interval); const [leverage, setLeverage] = useState("3"); const [marginAmount, setMarginAmount] = useState("10"); const [contracts, setContracts] = useState(""); const [reviewed, setReviewed] = useState(false); const [submitting, setSubmitting] = useState(false); const [reviewText, setReviewText] = useState("");
  const payload = () => ({ strategyId, interval, leverage: Number(leverage), marginAmount: Number(marginAmount), ...(contracts ? { contracts: Number(contracts) } : {}) });
  const review = async (): Promise<void> => { setSubmitting(true); setReviewText(""); try { const response = await fetch("/api/trade-review", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload()) }); const body = await response.json() as { error?: string; ai?: DashboardState["ai"] }; if (!response.ok) throw new Error(body.error ?? "AI 仓位审核失败"); setReviewed(true); setReviewText(body.ai?.latest?.summary ?? "AI 审核完成，可以确认下单"); } catch (error) { setReviewed(false); window.alert(error instanceof Error ? error.message : "AI 仓位审核失败"); } finally { setSubmitting(false); } };
  const trade = async (): Promise<void> => { setSubmitting(true); try { const response = await fetch("/api/trade", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ side: "BUY", ...payload() }) }); if (!response.ok) { const body = await response.json() as { error?: string }; throw new Error(body.error ?? "下单失败"); } setOpen(false); setReviewed(false); } catch (error) { window.alert(error instanceof Error ? error.message : "下单失败"); } finally { setSubmitting(false); } };
  const sell = async (): Promise<void> => { const response = await fetch("/api/trade", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ side: "SELL", strategyId, interval, leverage: Number(leverage), marginAmount: Number(marginAmount) }) }); if (!response.ok) { const body = await response.json() as { error?: string }; window.alert(body.error ?? "卖出失败"); } };
  const notional = (Number(marginAmount) || 0) * (Number(leverage) || 1); const price = state.market.latestPrice; const estimatedContracts = price > 0 ? notional / price : 0;
  return <><div className="grid grid-cols-2 gap-2"><button className="terminal-trade-button border-profit/40 bg-profit/10 text-profit" disabled={Boolean(state.position)} onClick={() => { setReviewed(false); setOpen(true); }}><ArrowUpFromLine size={14} />开多 / 买入</button><button className="terminal-trade-button border-loss/40 bg-loss/10 text-loss" disabled={!state.position} onClick={() => void sell()}><ArrowDownToLine size={14} />平多 / 卖出</button></div><Modal title="合约手动下单 · 先 AI 审核，再确认" visible={open} onCancel={() => { setOpen(false); setReviewed(false); }} footer={<div className="flex justify-end gap-2"><button className="terminal-trade-button border-line bg-hover text-ink" onClick={() => setOpen(false)}>取消</button>{reviewed ? <button className="terminal-trade-button border-profit/40 bg-profit/10 text-profit" disabled={submitting} onClick={() => void trade()}><CheckCircle2 size={14} />确认下单</button> : <button className="terminal-trade-button border-cyan/35 bg-cyan/8 text-cyan" disabled={submitting || !state.ai.enabled} onClick={() => void review()}><Brain size={14} />{submitting ? "AI 审核中…" : "AI 审核仓位"}</button>}</div>}>
    <div className="grid gap-3 py-2"><div className="rounded border border-cyan/25 bg-cyan/5 p-3 text-xs leading-5 text-cyan"><div className="flex items-center gap-2 font-semibold"><Brain size={14} />必须完成事前仓位审核</div><p className="m-0 mt-1 text-muted">AI 会结合可用余额、杠杆、名义价值、策略状态和当前持仓进行审查。AI 不会直接下单。</p></div><label className="grid gap-2 text-sm text-muted">交易策略<Select value={strategyId} optionList={state.strategies.map((item) => ({ value: item.id, label: item.name }))} onChange={(value) => { setStrategyId(String(value)); setReviewed(false); }} /></label><label className="grid gap-2 text-sm text-muted">允许周期<Select value={interval} optionList={options} onChange={(value) => { setInterval(String(value)); setReviewed(false); }} /></label><label className="grid gap-2 text-sm text-muted">杠杆倍数<Select value={leverage} optionList={leverages} onChange={(value) => { setLeverage(String(value)); setReviewed(false); }} /></label><label className="grid gap-2 text-sm text-muted">保证金金额（USDT）<input className="h-9 rounded border border-line bg-bg px-3 font-mono text-sm text-ink" type="number" min="0.01" step="0.01" value={marginAmount} onChange={(event) => { setMarginAmount(event.target.value); setReviewed(false); }} /></label><label className="grid gap-2 text-sm text-muted">合约张数（可选）<input className="h-9 rounded border border-line bg-bg px-3 font-mono text-sm text-ink" type="number" min="1" step="1" value={contracts} onChange={(event) => { setContracts(event.target.value); setReviewed(false); }} placeholder="按保证金×杠杆估算" /></label><div className="grid grid-cols-3 gap-2 rounded border border-line bg-bg/40 p-3 text-[10px] text-muted"><span><Calculator size={12} className="mb-1 text-cyan" />名义价值<strong className="mt-1 block font-mono text-ink">{notional.toFixed(2)} USDT</strong></span><span>预估 BTC<strong className="mt-1 block font-mono text-ink">{estimatedContracts.toFixed(6)}</strong></span><span>可用余额<strong className="mt-1 block font-mono text-ink">{state.account.quoteFree.toFixed(2)} USDT</strong></span></div>{reviewText && <div className="rounded border border-profit/25 bg-profit/5 p-3 text-xs leading-5 text-profit"><CheckCircle2 size={14} className="mb-1" />AI 审核结果：{reviewText}</div>}<p className="m-0 rounded border border-warning/25 bg-warning/6 p-3 text-xs leading-5 text-warning">{reviewed ? "参数已通过 AI 审核。请再次确认后才会调用 OKX 下单。" : `当前为 ${state.mode === "live" ? "真实盘" : "模拟盘"}，请先点击 AI 审核仓位。`}</p></div></Modal></>;
}
