import { TrendingDown, TrendingUp } from "lucide-react";
import type { ReactElement } from "react";
import type { DashboardState } from "../../../src/dashboard/dashboard-types";
import { Card } from "../ui/Card";
import { Tag } from "../ui/Tag";
import { MarketChart } from "../MarketChart";
import { MarketToolbar } from "./MarketToolbar";
import { formatMoney } from "../ui";
export function MarketOverview({ state, onIntervalChange }: { state: DashboardState; onIntervalChange: (interval: string) => void }): ReactElement { return <><MarketToolbar state={state} onIntervalChange={onIntervalChange} /><div className="section-heading chart-heading"><div><span className="eyebrow">MARKET INTELLIGENCE</span><h4 className="text-xl font-bold text-slate-100">行情与信号</h4></div><span className="section-note">均线、关键价位与策略触发点</span></div><Card className="chart-card"><div className="card-header"><div className="card-title"><h5 className="text-base font-semibold text-slate-100">{state.symbol} 行情</h5><div className="price-display"><span className="current-price">{state.market.latestPrice ? formatMoney(state.market.latestPrice) : "--"}</span><span className="quote-asset">{state.account.quoteAsset}</span></div></div><div className="signal-indicators"><Signal label="买入" signal={state.strategy.buy} type="buy" /><Signal label="卖出" signal={state.strategy.sell} type="sell" /></div></div><MarketChart state={state} levels={[...(state.strategy.support ? [{ price: state.strategy.support, title: "支撑位", color: "#d6a64b" }] : []), ...(state.strategy.resistance ? [{ price: state.strategy.resistance, title: "阻力位", color: "#79a7c4" }] : [])]} /></Card></>; }
function Signal({ label, signal, type }: { label: string; signal: string | null; type: "buy" | "sell" }): ReactElement { return <div className="signal-item"><p className="text-xs text-slate-500">{label}</p>{signal ? <Tag color={type === "buy" ? "green" : "red"}><span className="inline-flex items-center gap-1">{type === "buy" ? <TrendingUp size={12} /> : <TrendingDown size={12} />}{signal}</span></Tag> : <Tag>--</Tag>}</div>; }
