import { useCallback, useEffect, useState } from "react";
import type { ReactElement } from "react";
import { AlertTriangle } from "lucide-react";
import { Layout, SideSheet } from "@douyinfe/semi-ui";
import type { DashboardState } from "../src/dashboard/dashboard-types";
import { AccountCard } from "./components/dashboard/AccountCard";
import { AiAdvisorCard } from "./components/dashboard/AiAdvisorCard";
import { DashboardHeader } from "./components/dashboard/DashboardHeader";
import { MarketOverview } from "./components/dashboard/MarketOverview";
import { PositionCard } from "./components/dashboard/PositionCard";
import "./styles.css";

const { Content } = Layout;

const emptyState: DashboardState = { updatedAt: 0, mode: "demo", platform: "okx", symbol: "BTC-USDT", interval: "1d", instruments: [], connection: { market: false, userData: false, lastAccountUpdate: 0, error: null }, market: { latestPrice: 0, latestCandle: null, recentCandles: [], candleCount: 0, lastCandleTimestamp: 0 }, strategy: { buy: null, sell: null, trendFilter: null, entrySignal: null, support: null, resistance: null }, account: { balances: [], quoteAsset: "USDT", quoteFree: 0, quoteLocked: 0, baseAsset: "BTC", baseFree: 0, baseLocked: 0, estimatedEquity: 0 }, position: null, lastAction: null, activity: [], ai: { enabled: false, decisionMode: "advisory", model: "gpt-4o-mini", latest: null, history: [] } };

function useDashboardSocket(onState: (state: DashboardState) => void): "connecting" | "connected" | "offline" { const [status, setStatus] = useState<"connecting" | "connected" | "offline">("connecting"); useEffect(() => { let socket: WebSocket | null = null; let retry: number | undefined; const connect = () => { setStatus("connecting"); const protocol = window.location.protocol === "https:" ? "wss" : "ws"; socket = new WebSocket(`${protocol}://${window.location.host}/ws`); socket.onopen = () => setStatus("connected"); socket.onmessage = (event) => { const message = JSON.parse(event.data) as { type?: string; payload?: DashboardState }; if (message.type === "state" && message.payload) onState(message.payload); }; socket.onclose = () => { setStatus("offline"); retry = window.setTimeout(connect, 2500); }; socket.onerror = () => socket?.close(); }; connect(); return () => { if (retry) window.clearTimeout(retry); socket?.close(); }; }, [onState]); return status; }

export default function App(): ReactElement { const [state, setState] = useState(emptyState); const [activeNav, setActiveNav] = useState("dashboard"); const [switching, setSwitching] = useState(false); const [drawer, setDrawer] = useState<"wallet" | "ai" | null>(null); const onState = useCallback((next: DashboardState) => setState(next), []); const socketStatus = useDashboardSocket(onState); const onSymbolChange = useCallback(async (symbol: string) => { if (symbol === state.symbol || switching) return; setSwitching(true); try { const response = await fetch("/api/symbol", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ symbol }) }); const result = await response.json() as DashboardState | { error?: string }; if (!response.ok) throw new Error("error" in result ? result.error : "切换交易对失败"); setState(result as DashboardState); } catch (error) { window.alert(error instanceof Error ? error.message : "切换交易对失败"); } finally { setSwitching(false); } }, [state.symbol, switching]); return <Layout className="app-container"><DashboardHeader state={state} activeNav={activeNav} onNavChange={setActiveNav} onSymbolChange={onSymbolChange} onOpenWallet={() => setDrawer("wallet")} onOpenAi={() => setDrawer("ai")} /><Content className="app-content">{state.connection.error && <div className="error-card"><AlertTriangle size={16} /><span>账户余额读取失败: {state.connection.error}</span></div>}<main className="chart-stage"><MarketOverview state={state} /></main><SideSheet title="钱包与持仓" visible={drawer === "wallet"} onCancel={() => setDrawer(null)} width={390}><div className="drawer-stack"><AccountCard state={state} /><PositionCard state={state} /></div></SideSheet><SideSheet title="AI 策略审核" visible={drawer === "ai"} onCancel={() => setDrawer(null)} width={520}><AiAdvisorCard state={state} /></SideSheet></Content></Layout>; }
